version: '3.8'

services:
  swaggerapi:
    image: swaggerapi/swagger-editor:next-v5-unprivileged
    #image: swaggerapi/swagger-editor
    # platform: linux/amd64
    volumes:
      - ./:/tmp/
    environment:
      - "SWAGGER_FILE=/tmp/openapi.json"
    ports:
      - "50080:8080"
